# Generated by Django 4.2.13 on 2024-07-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('hitlevel', models.CharField(max_length=100)),
                ('damage', models.CharField(max_length=100)),
                ('startup', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('hit', models.CharField(max_length=100)),
                ('counterhit', models.CharField(max_length=100)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.characters')),
            ],
        ),
    ]
