# Generated by Django 4.2.13 on 2024-07-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
        migrations.RenameModel(
            old_name='Moves',
            new_name='Move',
        ),
    ]
