# Generated by Django 4.2.13 on 2024-07-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_characters_character_rename_moves_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='details',
            field=models.CharField(max_length=2000),
        ),
    ]
