# Generated by Django 4.2.13 on 2024-07-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_image_alter_character_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
